### PR TITLE
Final Responsive Page for tracks 

### PR DESCRIPTION
**Pull request by calebjubal**
the description for the tracks will be created as soon as we get the info

we will create a rupture animation on the vector with description

### CODE REVIEW

**Review by THEGAMECHANGER416 — CHANGES_REQUESTED** [review]
I feel this will cause merge conflicts with the oeiginal repo, can you make sure it is compatible with other changes.
Perhaps include a screen recording of how everything is looking?

**Comment by calebjubal** [comment]
ok

**Comment by calebjubal** [comment]
https://drive.google.com/file/d/118lfWTrtCVtutPEcVGuZtg0AdMdzkx-h/view?usp=sharing

kindly view the update made

**Comment by calebjubal** [comment]
There is a space left in the right side for description, which will be used when the cursor hovers over each topic for description expansion

**Comment by THEGAMECHANGER416** [comment]
Hey, just saw the tracks page, its good, Lets get it merged asap. Just need to resolve conflicts with the css

**Pull request merged**
