### PR TITLE
Website about page

### PR DESCRIPTION
**Pull request by nidhi752**
Thsi is the about page. It has one issue tho, I am unable to zoom into background picture, I want it zoomed enough so that the smallest circle is not too small and doesn't look hallucinating. I took inspo for the background design from this website.

https://www.alexbeigeweb.dev/

### CODE REVIEW

**Review by THEGAMECHANGER416 — CHANGES_REQUESTED** [review]
Can you Make it backwards compatible?
I mean integrate it with the existing site

**Comment by nidhi752** [comment]
I am unable to merge ache se tbh

**Comment by THEGAMECHANGER416** [comment]
> I am unable to merge ache se tbh

Can you tell the issue you are facing in detail?
Much better, you can share it on website group

**Comment by ParnikaMathur15** [comment]
@THEGAMECHANGER416 The merging issue has been addressed..will be sharing the files in a while

**Comment by THEGAMECHANGER416** [comment]
@nidhi752 @ParnikaMathur15 Just merged a new section of our website, can you please also make sure your section is compatible with that

**Comment by ParnikaMathur15** [comment]
> @nidhi752 @ParnikaMathur15 Just merged a new section of our website, can you please also make sure your section is compatible with that

Sure we'll work on it..

**Comment by ParnikaMathur15** [comment]
The timeline is not merging properly because of the position property to align about page alongside the table image.. Working on it..

**Comment by ParnikaMathur15** [comment]
@nidhi752  please push the most recent ones.

**Comment by ParnikaMathur15** [comment]
@nidhi752 please push the most recent ones for their feedback

**Comment by THEGAMECHANGER416** [comment]
@ParnikaMathur15 @nidhi752 If you need any help about any of the previous sections, feel free to reach out to me. I can get the leads in contact with you!

**Comment by nidhi752** [comment]
Hi, I have pushed latest files. Please provide feedback.

**Review by THEGAMECHANGER416 — APPROVED** [review]
Merged!!

**Pull request merged**
