### PR TITLE
Added the timeline component of the Code Cubicle 2.0 Website

### PR DESCRIPTION
**Pull request by Om-Mishra7**
ScrrenShot

### CODE REVIEW

**Comment by THEGAMECHANGER416** [comment]
@Om-Mishra7 Can you make this backward compatible? And also add it to index as a new section

**Review by THEGAMECHANGER416 — COMMENTED** [review]
@Om-Mishra7 Please confirm once that these changes have been tested locally with the existing files and No Errors were observed

**Comment by Om-Mishra7** [comment]
@THEGAMECHANGER416 Tested in dev, the timleine is responsive and all. The only issue is that the homepage in it's current iterations is not mobile responsive, so it affects the timeline's responsiveness but the timeline itself is fine.

**Comment by THEGAMECHANGER416** [comment]
> @THEGAMECHANGER416 Tested in dev, the timleine is responsive and all. The only issue is that the homepage in it's current iterations is not mobile responsive, so it affects the timeline's responsiveness but the timeline itself is fine.

The home page was responsive, last I checked. They also had a video demo of the home page. Can you include a video screen recording of how things are looking now?

**Comment by Om-Mishra7** [comment]
@THEGAMECHANGER416 I had not pulled the changes from the main branch, it's all good now.

**Comment by THEGAMECHANGER416** [comment]
@Om-Mishra7 Taking your word for it
Merged!!

**Pull request merged**
